name: Bug Report
description: Report a bug in the Admin Panel
title: '[Bug]: '
labels: ['bug', 'admin', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste image URLs

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment did this occur in?
      options:
        - Staging
        - Production
        - Local Development
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: e.g., Chrome 120, Safari 17, Firefox 121
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 14.2, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: If there are any console errors, please paste them here.
      placeholder: Paste any console errors...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other information that might be helpful...
