name: Feature Request
description: Suggest a new feature for the Admin Panel
title: '[Feature]: '
labels: ['enhancement', 'admin', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Should have
        - Must have
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Which user role would primarily benefit from this feature?
      options:
        - Super Admin
        - Admin
        - Coach
        - All roles
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Screenshots
      description: If you have any mockups or screenshots that help illustrate the feature, please add them here.
      placeholder: Drag and drop images here or describe the UI/UX

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any other information that might be helpful...
